server:
  port: 8080

spring:
  application:
    name: nimon-toy
  profiles:
    active: local
  security:
    enabled: false
  jpa:
    show_sql: true
    format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

---
spring:
  profiles: local


datasource:
  url: jdbc:mysql://localhost/
  db: nimontoy
  options: ?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
  username: root
  password: password


---
spring:
  profiles: dev


---
spring:
  profiles: docker