server:
  port: 8080

spring:
  application:
    name: nimon-toy
  profiles:
    active: local
  security:
    enabled: false
  jpa:
    show_sql: true
    format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

---
spring:
  profiles: local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:mysql://localhost:5432/postgresql
    username: postgresql
    password: password
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL8Dialect
  properties:
    hibernate:
      temp:
        useJdbcMetadataDefaults: false

---
spring:
  profiles: dev


---
spring:
  profiles: docker